{% set name = "fasteners" %}
{% set version = "0.19" %}
{% set sha256 = "b4f37c3ac52d8a445af3a66bce57b33b5e90b97c696b7b984f530cf8f0ded09c" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - fasteners

about:
  home: https://github.com/harlowja/fasteners
  license: Apache-2.0
  license_file: LICENSE
  summary: A python package that provides useful locks.

extra:
  recipe-maintainers:
    - alimanfoo
    - cmutel
    - jakirkham
