{% set name = "fasteners" %}
{% set version = "0.16.3" %}
{% set md5 = "243188fe770ad60e9da722bef9dc7a78" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  md5: {{ md5 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - six
    - monotonic >=0.1

  run:
    - python >=3.6
    - six
    - monotonic >=0.1

test:
  imports:
    - fasteners
    - fasteners.tests

about:
  home: https://github.com/harlowja/fasteners
  license: Apache-2.0
  license_file: LICENSE
  summary: A python package that provides useful locks.

extra:
  recipe-maintainers:
    - alimanfoo
    - cmutel
